### ISSUE TITLE
Error with numpy concatenate

### ISSUE THREAD

**Issue by aclaussen1** [supasorn/synthesizing_obama_network_training#3]
When I run the program, I am able to preprocess the data file but then I run into the error below. Any idea what the problem is? I printed the lst from np.concatenate(lst) to the console and it was quite long...

command i am running: python run.py --input2 /home/ec2-user/synthesizing_obama_network_training/obama_data/audio/normalized-cep13/zYGok_gHfY0.wav.npy --save_dir ./saveme

...
vIPUrZuLlCQ}}01
vIPUrZuLlCQ}}02
vIPUrZuLlCQ}}03
vIPUrZuLlCQ}}04
WjX0iJU3vtY (34257, 15) training
WjX0iJU3vtY}}00
WjX0iJU3vtY}}01
WjX0iJU3vtY}}02
WjX0iJU3vtY}}03
WjX0iJU3vtY}}04
WjX0iJU3vtY}}05
WjX0iJU3vtY}}06
WjX0iJU3vtY}}07
WjX0iJU3vtY}}08
kV_D6avFtdo (31768, 15) training
kV_D6avFtdo}}00
kV_D6avFtdo}}01
kV_D6avFtdo}}02
kV_D6avFtdo}}03
kV_D6avFtdo}}04
kV_D6avFtdo}}05
Traceback (most recent call last):
  File "run.py", line 225, in <module>
    main()
  File "run.py", line 222, in main
    s = Speech()
  File "run.py", line 42, in __init__
    self.loadData()
  File "/home/weclash247/synthesizing_obama_network_training/util.py", line 129, in loadData
    meani, stdi, meano, stdo = self.normalize(inps, outps)
  File "/home/weclash247/synthesizing_obama_network_training/util.py", line 103, in normalize
    meani, stdi = normalizeData(inps["training"], "save/" + self.args.save_dir, "statinput", ["fea%02d" % x for x i
n range(inps["training"][0].shape[1])], normalize=self.args.normalizeinput)
  File "/home/weclash247/synthesizing_obama_network_training/util.py", line 46, in normalizeData
    allstrokes = np.concatenate(lst)
MemoryError

I am running on a machine with little RAM.. I will try upgrading RAM and seeing if this fixes it.

**Comment by aclaussen1** [comment]
Upgrading RAM fixed the problem. I had 4gb, moved to 16gb
